### ISSUE TITLE
Project do not run. 

### ISSUE THREAD

**Issue by mbilalbark** [setchi/Unity-ShaderSketches#1]
I was not run project, because this project readme file not enough. For example i dont understand menu script variable menu root and container which assing game objects.

**Comment by setchi** [comment]
@mbilalbark 
Thank you for the report.
Please open the scene and play it.
Assets/ShaderSketches/Showcase.unity

**Comment by mbilalbark** [comment]
Thanks for answers 👍

**Comment by setchi** [comment]
@mbilalbark I wrote it in the README.
https://github.com/setchi/Unity-ShaderSketches/commit/b41b630b320b6b15c67f72fd6aa3752362b9571f

Thanks.
